runs:
  using: "composite"
    steps:
    - name: Create manifest for install Wazuh stack
      shell: bash
      run: |
        hostname=$(sudo puppetserver ca list --all | awk '{if(NR>1)print $1;}')
        sudo echo "127.0.0.1 "$hostname | sudo tee -a /etc/hosts > /dev/null
        sudo echo "node "\"$hostname\"" {" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp  > /dev/null
        sudo echo "class {'wazuh::manager':} ->  class {'wazuh::indexer':} -> class {'wazuh::filebeat_oss':} -> class {'wazuh::dashboard':}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo cat /etc/puppetlabs/code/environments/production/manifests/stack.pp

    - name: Install Wazuh Stack
      shell: bash
      run: sudo bash -c 'puppet agent -tod || test $? -eq 2'